### create a parcel
POST http://localhost:3030/add-parcel
Content-Type: application/json

{
    "numberOrCode": "M-004",
    "parcelType": "equipment type",
    "parcelName": "Computer office 4",
    "brandTypeModelSizeDescrip": "Lenovo",
    "unitPrice": 20000,
    "howToGet": "Money Support 2025",
    "parcelRemark": "Testing System"
}

### get parcels
GET http://localhost:3030/get-all-parcel

### get a parcel
GET http://localhost:3030/get-parcel/684ab5c06ebc582cb75ce1ef

### update a parcels
PUT http://localhost:3030/edit-parcel/684ab6896ebc582cb75ce1f4
Content-Type: application/json

{
    "numberOrCode": "A-003",
    "parcelType": "equipment type",
    "parcelName": "LenoveName1",
    "brandTypeModelSizeDescrip": "Lenove",
    "unitPrice": 37000,
    "howToGet": "Money Support 2024",
    "ParcelRemark": "Testing System"
}

### delete a parcel
DELETE http://localhost:3030/delete-parcel/68499adb7da3d215b0c07dd5

### filter parcels
# GET http://localhost:3030/filter-parcels?parcelName=
GET http://localhost:3030/filter-parcels?parcelName=LenoveName1