### create a parcel
POST http://localhost:3030/add-parcel
Content-Type: application/json

{
    "numberOrCode": "M-004",
    "parcelType": "equipment type",
    "parcelName": "Computer office 4",
    "brandTypeModelSizeDescrip": "Lenovo",
    "unitPrice": 20000,
    "howToGet": "Money Support 2025",
    "parcelRemark": "Testing System"
}

### get parcels
GET http://localhost:3030/get-all-parcel

### update a parcels
PUT http://localhost:3030/edit-parcle/68499b217da3d215b0c07dd8
Content-Type: application/json

{
    "numberOrCode": "M-002",
    "parcelType": "equipment type",
    "parcelName": "Computer office 2",
    "brandTypeModelSizeDescrip": "Mac Book 2",
    "unitPrice": 7000,
    "howToGet": "Money Support 2024",
    "ParcelRemark": "Testing System"
}

### delete a parcel
DELETE http://localhost:3030/delete-parcle/68499b217da3d215b0c07dd8