### create a parcel
POST http://localhost:3030/add-parcel
Content-Type: application/json

{
    "numberOrCode": "M-003",
    "parcelType": "equipment type",
    "parcelName": "Computer office 2",
    "brandTypeModelSizeDescrip": "Sony",
    "unitPrice": 15000,
    "howToGet": "Money Support 2025",
    "ParcelRemark": "Testing System"
}

### get parcels
GET http://localhost:3030/get-all-parcel

### update a parcels
PUT http://localhost:3030/edit-parcle/683c913c5cdf2c045b0c02b5
Content-Type: application/json

{
    "numberOrCode": "M-002",
    "parcelType": "equipment type",
    "parcelName": "Computer office 2",
    "brandTypeModelSizeDescrip": "Mac Book 2",
    "unitPrice": 7000,
    "howToGet": "Money Support 2024",
    "ParcelRemark": "Testing System"
}

### delete a parcel
DELETE http://localhost:3030/delete-parcle/683c94a9ec8a24b95c9824a0